username: JimmyShi22
baseurl: /myblog
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
safe: false
highlighter: pygments
title: Jimmy Blog 
description: Welcome!
theme: modernist
disqusname: MyBlog
comments: true

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
