username: JimmyShi22
baseurl: /MyBlog
markdown: redcarpet
safe: false
highlighter: pygments
title: Jimmy Blog 
description: Welcome!
theme: minimal
disqusname: JimmyShi22
comments: true

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
